### ISSUE TITLE
Pooling on Microsoft ODBC Driver 13 (Preview) for SQL Server on Linux intermitent bug

### ISSUE THREAD

**Issue by andremoniz** [Azure/unixODBC-MSSQL#1]
When i add Pooling = YES in /etc/odbcinst.ini in  ubuntu 14.04
[ODBC]
Trace       = Yes
Trace File      = /tmp/sql.log
Pooling = Yes

[ODBC Driver 13 for SQL Server]
Description=Microsoft ODBC Driver 13 for SQL Server
Driver=/opt/microsoft/msodbcsql/lib64/libmsodbcsql-13.0.so.0.0
Threading=1
UsageCount=1
CPTimeout       = 120

I get intermitent errors (50% of the times it works) in my api

The log file  /tmp/sql.log

gives me error on the first query

[ODBC][4821][1462555943.759118][__handles.c][450]
        Exit:[SQL_SUCCESS]
            Environment = 0x7fb9e72145b0
[ODBC][4821][1462555943.759201][SQLSetEnvAttr.c][182]
        Entry:  
            Environment = 0x7fb9e72145b0  
            Attribute = SQL_ATTR_ODBC_VERSION  
            Value = 0x3  
            StrLen = 0
[ODBC][4821][1462555943.759224][SQLSetEnvAttr.c][349]
        Exit:[SQL_SUCCESS]
[ODBC][4821][1462555943.759262][SQLSetEnvAttr.c][182]
        Entry:  
            Environment = 0x7fb9e72145b0  
            Attribute = SQL_ATTR_CP_MATCH  
            Value = (nil)  
            StrLen = 0
[ODBC][4821][1462555943.759287][SQLSetEnvAttr.c][349]
        Exit:[SQL_SUCCESS]
[ODBC][4821][1462555943.759305][SQLAllocHandle.c][364]
        Entry:
            Handle Type = 2
            Input Handle = 0x7fb9e72145b0
[ODBC][4821][1462555943.759322][SQLAllocHandle.c][482]
        Exit:[SQL_SUCCESS]
            Output Handle = 0x7fb9e72155f0
[ODBC][4821][1462555943.759342][SQLSetConnectAttr.c][321]
        Entry:  
            Connection = 0x7fb9e72155f0  
            Attribute = SQL_ATTR_AUTOCOMMIT  
            Value = 0x1  
            StrLen = -6
[ODBC][4821][1462555943.759358][SQLSetConnectAttr.c][504]
        Exit:[SQL_SUCCESS]
[ODBC][4821][1462555943.759375][SQLSetConnectAttr.c][321]
        Entry:  
            Connection = 0x7fb9e72155f0  
            Attribute = SQL_ATTR_ODBC_CURSORS  
            Value = (nil)  
            StrLen = -6
[ODBC][4821][1462555943.759392][SQLSetConnectAttr.c][504]
        Exit:[SQL_SUCCESS]
[ODBC][4821][1462555943.759410][SQLConnect.c][3615]
        Entry:  
            Connection = 0x7fb9e72155f0  
            Server Name = [mssql][length = 5 (SQL_NTS)]  
            User Name = [sa][length = 2 (SQL_NTS)]  
            Authentication = [**********][length = 10 (SQL_NTS)]
[ODBC][4821][1462555943.759429][SQLConnect.c][3744]
        Exit:[SQL_SUCCESS]
[ODBC][4821][1462555943.760886][SQLAllocHandle.c][529]
        Entry:
            Handle Type = 3
            Input Handle = 0x7fb9e72155f0
[ODBC][4821][1462555943.760929][SQLAllocHandle.c][1064]
        Exit:[SQL_SUCCESS]
            Output Handle = 0x7fb9e7217440
[ODBC][4821][1462555943.760953][SQLPrepare.c][192]
        Entry:  
            Statement = 0x7fb9e7217440  
            SQL = [select top 1 \* from [artists] where [slug] = ? and [artists].[deleted_at] is null][length = 81 (SQL_NTS)]
[ODBC][4821][1462555943.760981][SQLPrepare.c][324]Error: IM001

IM001 should be function not found but this is akward.
Can someone help?

**Comment by meet-bhagdev** [comment]
Hello @andremoniz
Happy to help you out here. Do you have a repro script that you can share? Can you confirm this behavior on Ubuntu 15.x. Feel free to email me - meetb@microsoft.com

**Comment by andremoniz** [comment]
Hi @meet-bhagdev,
I will confirm in ubuntu 15.x. 
But can you please try it out in 14.04? 
I do not have a script this is a laravel 5.2 project with some queries to sql server database.
We use php odbc to connect and microsoft driver.
This error only happens when I activate pooling

**Comment by andremoniz** [comment]
bump
Hi @meet-bhagdev did you add the time to check this?
We are live now with the new driver and things seems fine without Connection Pooling.

**Comment by meet-bhagdev** [comment]
Hello @andremoniz 
Apologies as we have not been able to get to the root of it. We are actively looking at it and will let you as soon as we have something to share. Thanks!

**Comment by meet-bhagdev** [comment]
@andremoniz : What version of unixODBC version are you using? 2.3.0, 2.3.1 or something else?

**Comment by andremoniz** [comment]
unixODBC 2.3.1
